stages:
  - deployment

deployment:
  stage: deployment
  only:
    - master
  script:
    - echo "正在部署中"
    - TAG=$(date "+%Y%m%d%H%M%S")
    - docker build -t ssr:latest .
    - docker run -p 49160:80 -d ssr:latest
    - echo "部署完毕"



